version: '3.1'
services:
  dynamo:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./data:/home/dynamodblocal/data
    ports:
      - 8000:8000