version: '3.1'

services:

  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
