version: '3'
services:
  server:
    image: nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${DIRECTORY}:/var/www/html
