version: '3.1'
services:
  minio:
    image: 'minio/minio'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - ./data:/data
    command: server /data
    ports:
      - 9000:9000
